### ISSUE TITLE
How Did You Find The Documentation on `AddAssemblyInfo` `Dictionary`

### ISSUE THREAD

**Issue by mattcargile** [jborean93/PowerShell-ALC#2]
Great project. This is really helpful to understand. All the `README.md`'s are really nice for someone as green as me.

I was curious. How did you come up with this object in the _add_ method? I assume adding this data to the object allows the runtime to resolve the correct assembly?

https://github.com/jborean93/PowerShell-ALC/blob/2ce581fab68c801988fbcea716b1141d64d5ea37/ALCResolver/src/ALCResolver.Private/SharedUtil.cs#L12-L24

I read the below MS docs.

https://learn.microsoft.com/en-us/dotnet/core/dependency-loading/understanding-assemblyloadcontext
https://learn.microsoft.com/en-us/dotnet/api/system.runtime.loader.assemblyloadcontext?view=net-8.0

**Comment by jborean93** [comment]
This is just a custom method that just adds the key `Assembly` to the provided dictionary so it get's serialized for the JSON output. There is nothing too specific to the ALC side just that it gets the following details

+ `Name` - The same of the assembly the type provided is loaded in
+ `ALC` - The name of the ALC the type is loaded in (if it was in an ALC)
+ `Location` - The location of the DLL of the assembly the type is loaded in

Is there something specific that you wanted clarification on?

**Comment by mattcargile** [comment]
Oh that helps. I thought it was some requirement for the runtime to be able to know which _ALC_ to use or something. Not sure if that makes sense. So it is strictly for output and demo purposes?

**Comment by jborean93** [comment]
Yep, the runtime type lookup works like normal in the ALC the assembly was loaded in. This particular function is for demo purposes to show that the JSON library was loaded in an ALC.

**Comment by mattcargile** [comment]
Gotcha; makes sense. Thanks.  :-)
