### ISSUE TITLE
Does ALC Resolver need a Wrapper assembly?

### ISSUE THREAD

**Issue by mdgrs-mei** [jborean93/PowerShell-ALC#3]
The ALC Resolver approach looks like different from both:

A. [Resolving event with ALC](https://github.com/daxian-dbw/PowerShell-ALC-Samples/tree/main/Resolving-Event-with-ALC) (Cons: existing higher version assemblies will be used)
B. [Most robust solution](https://learn.microsoft.com/en-us/powershell/scripting/dev-cross-plat/resolving-dependency-conflicts?view=powershell-7.4#more-robust-solutions) (Cons: needs wrapper assembly)

and inheriting the cons from both.

I think your ALC Resolver approach does not need the wrapper dll and it can directly call the dependencies from cmdlets (same as A). Or, if we create a wrapper dll, we can make the deps to be always loaded in the custom ALC by placing `ALCResolver.Private.dll` and deps dlls one folder deeper and also loading the `ALCResolver.Private.dll` to the custom ALC (That's is the approach B).

(I haven't run your code yet so sorry if I'm wrong.)

**Comment by jborean93** [comment]
In most cases this would be fine but there is a risk that your assembly itself is going to cause one of the dependencies to be loaded before PowerShell calls the `OnImport` method in `IModuleAssemblyInitializer`. Here is a diff that I tested out locally but it shows you how this could result in a dependency not being loaded in the ALC.

<details>

<summary>Expand for diff</summary>

```diff
diff --git a/ALCResolver-2/build.ps1 b/ALCResolver-2/build.ps1
new file mode 100644
index 0000000..45d4700
--- /dev/null
+++ b/ALCResolver-2/build.ps1
@@ -0,0 +1,3 @@
+. $PSScriptRoot/../common.ps1
+
+Invoke-ModuleBuild -Path $PSScriptRoot
diff --git a/ALCResolver-2/module/ALCResolver.psd1 b/ALCResolver-2/module/ALCResolver.psd1
new file mode 100644
index 0000000..7da2584
--- /dev/null
+++ b/ALCResolver-2/module/ALCResolver.psd1
@@ -0,0 +1,24 @@
+@{
+    RootModule = 'bin/net8.0/ALCResolver.dll'
+    ModuleVersion = '1.0.0'
+    GUID = '31bb040b-32c8-4c89-a65e-876222ec94bc'
+    Author = 'Jordan Borean'
+    CompanyName = 'Community'
+    Copyright = '(c) 2023 Jordan Borean. All rights reserved.'
+    Description = 'ALC Resolver example'
+    PowerShellVersion = '5.1'
+    DotNetFrameworkVersion = '4.7.2'
+    TypesToProcess = @()
+    FormatsToProcess = @()
+    NestedModules = @()
+    FunctionsToExport = @()
+    CmdletsToExport = @(
+        'ConvertTo-NewtonsoftJson'
+        'ConvertTo-YamlDotNet'
+    )
+    VariablesToExport = @()
+    AliasesToExport = @()
+    PrivateData = @{
+        PSData = @{}
+    }
+}
diff --git a/ALCResolver-2/src/ALCResolver/ALCResolver.csproj b/ALCResolver-2/src/ALCResolver/ALCResolver.csproj
new file mode 100644
index 0000000..e525288
--- /dev/null
+++ b/ALCResolver-2/src/ALCResolver/ALCResolver.csproj
@@ -0,0 +1,32 @@
+<Project Sdk="Microsoft.NET.Sdk">
+
+  <PropertyGroup>
+    <TargetFrameworks>net8.0</TargetFrameworks>
+    <LangVersion>10.0</LangVersion>
+    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
+    <Nullable>enable</Nullable>
+  </PropertyGroup>
+
+  <ItemGroup Condition=" '$(TargetFramework)' == 'net8.0' ">
+    <!--
+    For PowerShell 7 we can load S.M.A at the version desired. This allows us
+    to use newer features with preprocessor directives. The PrivateAssets must
+    be set to all as PowerShell provides these assets at runtime.
+    -->
+    <PackageReference Include="System.Management.Automation" Version="7.1.0" PrivateAssets="all" />
+  </ItemGroup>
+
+  <ItemGroup Condition=" '$(TargetFramework)' == 'net472' ">
+    <!--
+    For PowerShell 5.1 we reference the standard library which provides a
+    baseline API for WinPS 5.1 and PS 7+. The PrivateAssets must also be set
+    to all as PowerShell provides them at runtime.
+    -->
+    <PackageReference Include="PowerShellStandard.Library" Version="5.1.0" PrivateAssets="all" />
+  </ItemGroup>
+
+  <ItemGroup>
+    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
+    <PackageReference Include="YamlDotNet" Version="13.7.1" />
+  </ItemGroup>
+</Project>
diff --git a/ALCResolver-2/src/ALCResolver/ConvertToNewtonsoftJsonCommand.cs b/ALCResolver-2/src/ALCResolver/ConvertToNewtonsoftJsonCommand.cs
new file mode 100644
index 0000000..456afcf
--- /dev/null
+++ b/ALCResolver-2/src/ALCResolver/ConvertToNewtonsoftJsonCommand.cs
@@ -0,0 +1,38 @@
+using System;
+using System.Collections.Generic;
+using System.Management.Automation;
+
+namespace ALCResolver;
+
+[Cmdlet(VerbsData.ConvertTo, "NewtonsoftJson")]
+[OutputType(typeof(string))]
+public sealed class ConvertToNewtonsoftJsonCommand : PSCmdlet
+{
+    private List<object> _objs = new();
+
+    [Parameter(
+        Mandatory = true,
+        ValueFromPipeline = true,
+        Position = 0
+    )]
+    public object[] InputObject { get; set; } = Array.Empty<object>();
+
+    protected override void ProcessRecord()
+    {
+        foreach (object obj in InputObject)
+        {
+            _objs.Add(obj);
+        }
+    }
+
+    protected override void EndProcessing()
+    {
+        Dictionary<string, object> finalObj = new()
+        {
+            {
+                "Object", _objs
+            }
+        };
+        WriteObject(Json.ConvertToJson(finalObj));
+    }
+}
diff --git a/ALCResolver-2/src/ALCResolver/ConvertToYamlDotNetCommand.cs b/ALCResolver-2/src/ALCResolver/ConvertToYamlDotNetCommand.cs
new file mode 100644
index 0000000..8378c8d
--- /dev/null
+++ b/ALCResolver-2/src/ALCResolver/ConvertToYamlDotNetCommand.cs
@@ -0,0 +1,49 @@
+using System;
+using System.Collections.Generic;
+using System.Management.Automation;
+using YamlDotNet.Core;
+using YamlDotNet.RepresentationModel;
+using YamlDotNet.Serialization;
+
+namespace ALCResolver;
+
+public class AAAA : INodeDeserializer
+{
+    public bool Deserialize(IParser parser, Type expectedType, Func<IParser, Type, object?> nestedObjectDeserializer, out object? result)
+    {
+        throw new NotImplementedException();
+    }
+}
+
+[Cmdlet(VerbsData.ConvertTo, "YamlDotNet")]
+[OutputType(typeof(string))]
+public sealed class ConvertToYamlDotNetCommand : PSCmdlet
+{
+    private List<object> _objs = new();
+
+    [Parameter(
+        Mandatory = true,
+        ValueFromPipeline = true,
+        Position = 0
+    )]
+    public object[] InputObject { get; set; } = Array.Empty<object>();
+
+    protected override void ProcessRecord()
+    {
+        foreach (object obj in InputObject)
+        {
+            _objs.Add(obj);
+        }
+    }
+
+    protected override void EndProcessing()
+    {
+        Dictionary<string, object> finalObj = new()
+        {
+            {
+                "Object", _objs
+            }
+        };
+        WriteObject(Yaml.ConvertToYaml(finalObj));
+    }
+}
diff --git a/ALCResolver-2/src/ALCResolver/Json.cs b/ALCResolver-2/src/ALCResolver/Json.cs
new file mode 100644
index 0000000..e16c71d
--- /dev/null
+++ b/ALCResolver-2/src/ALCResolver/Json.cs
@@ -0,0 +1,18 @@
+using System;
+using System.Collections.Generic;
+// We can reference our ALC dependency directly
+using Newtonsoft.Json;
+
+namespace ALCResolver;
+
+internal static class Json
+{
+    public static string ConvertToJson(Dictionary<string, object> data)
+    {
+        SharedUtil.AddAssemblyInfo(typeof(JsonConvert), data);
+
+        return JsonConvert.SerializeObject(
+            data,
+            Formatting.Indented);
+    }
+}
diff --git a/ALCResolver-2/src/ALCResolver/OnImportAndRemove.cs b/ALCResolver-2/src/ALCResolver/OnImportAndRemove.cs
new file mode 100644
index 0000000..ddb077b
--- /dev/null
+++ b/ALCResolver-2/src/ALCResolver/OnImportAndRemove.cs
@@ -0,0 +1,75 @@
+using System;
+using System.IO;
+using System.Management.Automation;
+using System.Reflection;
+using System.Runtime.Loader;
+
+namespace ALCResolver;
+
+internal class LoadContext : AssemblyLoadContext
+{
+    private readonly string _assemblyDir;
+
+    public LoadContext(string assemblyDir)
+        : base (name: "ALCResolver", isCollectible: false)
+    {
+        _assemblyDir = assemblyDir;
+    }
+
+    protected override Assembly? Load(AssemblyName assemblyName)
+    {
+        string asmPath = Path.Join(_assemblyDir, $"{assemblyName.Name}.dll");
+        if (File.Exists(asmPath))
+        {
+            return LoadFromAssemblyPath(asmPath);
+        }
+        else
+        {
+            return null;
+        }
+    }
+}
+
+public class OnModuleImportAndRemove : IModuleAssemblyInitializer, IModuleAssemblyCleanup
+{
+    private static readonly string _assemblyDir = Path.GetDirectoryName(
+        typeof(OnModuleImportAndRemove).Assembly.Location)!;
+
+    private static readonly LoadContext _alc = new LoadContext(_assemblyDir);
+
+    public void OnImport()
+    {
+        AssemblyLoadContext.Default.Resolving += ResolveAlc;
+    }
+
+    public void OnRemove(PSModuleInfo module)
+    {
+        AssemblyLoadContext.Default.Resolving -= ResolveAlc;
+    }
+
+    private static Assembly? ResolveAlc(AssemblyLoadContext defaultAlc, AssemblyName assemblyToResolve)
+    {
+        string asmPath = Path.Join(_assemblyDir, $"{assemblyToResolve.Name}.dll");
+        if (IsSatisfyingAssembly(assemblyToResolve, asmPath))
+        {
+            return _alc.LoadFromAssemblyName(assemblyToResolve);
+        }
+        else
+        {
+            return null;
+        }
+    }
+
+    private static bool IsSatisfyingAssembly(AssemblyName requiredAssemblyName, string assemblyPath)
+    {
+        if (!File.Exists(assemblyPath))
+        {
+            return false;
+        }
+
+        AssemblyName asmToLoadName = AssemblyName.GetAssemblyName(assemblyPath);
+
+        return string.Equals(asmToLoadName.Name, requiredAssemblyName.Name, StringComparison.OrdinalIgnoreCase)
+            && asmToLoadName.Version >= requiredAssemblyName.Version;
+    }
+}
\ No newline at end of file
diff --git a/ALCResolver-2/src/ALCResolver/SharedUtil.cs b/ALCResolver-2/src/ALCResolver/SharedUtil.cs
new file mode 100644
index 0000000..0fedbff
--- /dev/null
+++ b/ALCResolver-2/src/ALCResolver/SharedUtil.cs
@@ -0,0 +1,23 @@
+using System;
+using System.Collections.Generic;
+using System.Reflection;
+using System.Runtime.Loader;
+
+namespace ALCResolver;
+
+internal class SharedUtil
+{
+    public static void AddAssemblyInfo(Type type, Dictionary<string, object> data)
+    {
+        Assembly asm = type.Assembly;
+
+        data["Assembly"] = new Dictionary<string, object?>()
+        {
+            { "Name", asm.GetName().FullName },
+#if NET5_0_OR_GREATER
+            { "ALC", AssemblyLoadContext.GetLoadContext(asm)?.Name },
+#endif
+            { "Location", asm.Location }
+        };
+    }
+}
diff --git a/ALCResolver-2/src/ALCResolver/Yaml.cs b/ALCResolver-2/src/ALCResolver/Yaml.cs
new file mode 100644
index 0000000..b1a2bc3
--- /dev/null
+++ b/ALCResolver-2/src/ALCResolver/Yaml.cs
@@ -0,0 +1,18 @@
+using System;
+using System.Collections.Generic;
+using YamlDotNet.RepresentationModel;
+using YamlDotNet.Serialization;
+
+namespace ALCResolver;
+
+internal static class Yaml
+{
+    public static string ConvertToYaml(Dictionary<string, object> data)
+    {
+        SharedUtil.AddAssemblyInfo(typeof(SerializerBuilder), data);
+
+        SerializerBuilder builder = new SerializerBuilder();
+        ISerializer serializer = builder.Build();
+        return serializer.Serialize(data);
+    }
+}
diff --git a/ALCResolver-2/test.ps1 b/ALCResolver-2/test.ps1
new file mode 100644
index 0000000..6bacc6d
--- /dev/null
+++ b/ALCResolver-2/test.ps1
@@ -0,0 +1,16 @@
+Import-Module -Name $PSScriptRoot\output\ALCResolver.psd1
+
+ConvertTo-NewtonsoftJson foo
+
+ConvertTo-YamlDotNet bar
+
+[System.AppDomain]::CurrentDomain.GetAssemblies() |
+    Where-Object { $_.GetName().Name -like "*json*" -or $_.GetName().Name -like "*yaml*" } |
+    ForEach-Object {
+        $alc = [Runtime.Loader.AssemblyLoadContext]::GetLoadContext($_)
+        [PSCustomObject]@{
+            Name = $_.FullName
+            Location = $_.Location
+            ALC = $alc
+        }
+    } | Format-List
\ No newline at end of file
```

</details>

The key thing I changed was adding a new type that was sub-classing `YamlDotNet`. Doing this cause .NET to resolve the `YamlDotNet` dependency when my module assembly was loaded.

```csharp
public class AAAA : INodeDeserializer
{
    public bool Deserialize(IParser parser, Type expectedType, Func<IParser, Type, object?> nestedObjectDeserializer, out object? result)
    {
        throw new NotImplementedException();
    }
}
```

The output when running `test.ps1`

```
{
  "Object": [
    "foo"
  ],
  "Assembly": {
    "Name": "Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed",
    "ALC": "Default",
    "Location": "/home/jborean/.local/powershell/Newtonsoft.Json.dll"
  }
}
Object:
- bar
Assembly:
  Name: YamlDotNet, Version=13.0.0.0, Culture=neutral, PublicKeyToken=ec19458f3c15af5e
  ALC: Default
  Location: /home/jborean/dev/PowerShell-ALC/ALCResolver-2/output/bin/net8.0/YamlDotNet.dll


Name     : Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
Location : /home/jborean/.local/powershell/Newtonsoft.Json.dll
ALC      : "Default" System.Runtime.Loader.DefaultAssemblyLoadContext #0

Name     : YamlDotNet, Version=13.0.0.0, Culture=neutral, PublicKeyToken=ec19458f3c15af5e
Location : /home/jborean/dev/PowerShell-ALC/ALCResolver-2/output/bin/net8.0/YamlDotNet.dll
ALC      : "Default" System.Runtime.Loader.DefaultAssemblyLoadContext #0
```

I have no idea if the type enumeration order is documented or whether there are other cases that could cause .NET to load a dependency at import time; attributes from dependency, static field with a dependency type, etc. But by not setting up the ALC resolver before importing the assembly that has the dependency you run the risk of accidentally loading the dep in the default context. So it could be fine but it also could not, hence why I found it safer to ensure the example didn't do it.

Ultimately the approach that you are looking for is pretty much the recommended [ALCLoader](https://github.com/jborean93/PowerShell-ALC/tree/main/ALCLoader) approach where an initial assembly is loaded to setup the ALC and other types shared by the module and the Default space is loaded and then the cmdlet which can call the deps directly is loaded into the ALC.

**Comment by mdgrs-mei** [comment]
I didn't know that there are cases where dependencies are loaded before the ALC setup. Now I understand the reason, thank you!

This is a suggestion but if we need a wrapper assembly, isn't the
[more robust solution](https://learn.microsoft.com/en-us/powershell/scripting/dev-cross-plat/resolving-dependency-conflicts?view=powershell-7.4#more-robust-solutions) better as a competitor to the ALC Loader approach? 

Modifications to ALC Resolver would be:

- Move `ALCResolver.Private.dll` and deps dlls under bin/deps/
- Load `ALCResolver.Private.dll` into ALC

With these small changes you can make deps always loaded in ALC. To be clear, I agree that the ALC Loader should be the best solution. Just wanted to make this repo a good list of solutions.

**Comment by jborean93** [comment]
> I didn't know that there are cases where dependencies are loaded before the ALC setup. Now I understand the reason, thank you!

That's all good, it's definitely an edge case and my first ALC module I wrote used this approach. Most people probably won't hit it but it's one of those you won't know it happening and trying to pivot to the `ALCLoader` style may be too hard so best to avoid getting into the scenario anyway.

> isn't the
[more robust solution](https://learn.microsoft.com/en-us/powershell/scripting/dev-cross-plat/resolving-dependency-conflicts?view=powershell-7.4#more-robust-solutions) better as a competitor to the ALC Loader approach?

Unless I'm wrong the more robust solution indicated there is the [ALCResolver](https://github.com/jborean93/PowerShell-ALC/tree/main/ALCResolver) approach. Based on the image

![image](https://github.com/user-attachments/assets/5879287b-825f-4415-bec9-8ba2a984db8a)

+ `AlcModule.Cmdlets.dll` is the same as `ALCResolver.dll` - contains the cmdlet and ALC resolver setup code
+ `AlcModule.Engine.dll` is the same as `ALCResolver.Private.dll` - contains the deps to the 3rd party assemblies and bridge code `ALCResolver.dll` will then call

It still has the same pros and cons stated by the `ALCResolver` page but it will ensure the assembly is not going to be loaded in the default context as the resolver is setup before the assembly itself is loaded. The modifications you've suggested just moves the deps to a new folder, I don't believe it changes anything else. The reason why deps aren't guaranteed to be loaded into an ALC if it's already present in the "Default" one is not because the deps are in the same folder but due to how the resolving event is setup.

With `ALCResolver` it is hooking into the "Default" ALC resolving event as shown in the robust solution `AssemblyLoadContext.Default.Resolving += ResolveAlcEngine;` and our example.

https://github.com/jborean93/PowerShell-ALC/blob/2ce581fab68c801988fbcea716b1141d64d5ea37/ALCResolver/src/ALCResolver/OnImportAndRemove.cs#L44

The [AssemblyLoadContext.Resolving](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.loader.assemblyloadcontext.resolving?view=net-9.0) event is only called if an assembly failed to be resolved normally and we use it to hook into the new ALC to resolve the assembly and return that `Assembly` object from the ALC

> Occurs when the resolution of an assembly fails when attempting to load into this assembly load context.

Compare that to the `ALCLoader` approach where we setup the ALC object in the initially loaded assembly like [LoadContext](https://github.com/jborean93/PowerShell-ALC/blob/main/ALCLoader/src/ALCLoader.Shared/LoadContext.cs). We then ask that `LoadContext` to resolve our assembly with the cmdlets and dependencies we want inside the ALC and returns the `Assembly` object for that. This has no connection to the existing "Default" assembly so any deps being requested will always go through the `LoadContext` even if it's loaded in the "Default" one.

> Just wanted to make this repo a good list of solutions.

Definitely appreciate the comments, you've certainly made me question my examples here and having to create examples that actually prove the cons is always good. Certainly good to get feedback to figure out more improvements to this process as it's currently a bit too complicated for most people and is the reason why I opened this repo.

**Comment by mdgrs-mei** [comment]
The biggest difference is that the robust solution loads ALCResolver.Private.dll to the custom ALC, not the default ALC.

My understanding is that the resolver event only loads the ALCResolver.Private.dll and the default logic in the custom ALC resolves the deps dlls in the same directly.

I used this approach in [PowerShellRun](https://github.com/mdgrs-mei/PowerShellRun/blob/bbad8e447b24ea5844ed30b2f988d12a116d3bb2/src/PowerShellRun/ALC/CustomAssemblyLoadContext.cs#L15) too.

**Comment by jborean93** [comment]
> The biggest difference is that the robust solution loads ALCResolver.Private.dll to the custom ALC, not the default ALC.

That's what `ALCResolver` does? The `ALCResolver.Private.dll` is the same as `AlcModule.Engine.dll`, is there a specific thing in the code you see as different that I am not seeing?

**Comment by mdgrs-mei** [comment]
In your ALC Resolver, you are skipping ALCResolver.Private.dll 
[here](https://github.com/jborean93/PowerShell-ALC/blob/2ce581fab68c801988fbcea716b1141d64d5ea37/ALCResolver/src/ALCResolver/OnImportAndRemove.cs#L67) right? That should load it to the default ALC.

**Comment by jborean93** [comment]
Hmm you are right, I think that might be a typo and is mean to be `ALCResolver` so that it doesn't try and resolve the current assembly in the ALC but even then that shouldn't fire anyway. I'll have to play around with it but it certainly seems wrong.

**Comment by mdgrs-mei** [comment]
I assumed it was intentional. If it's just a mistake, that explains it all!

I think the condition is fliped. This might also work:

```csharp
if (requiredAssemblyName.Name != "ALCResolver.Private" || !File.Exists(assemblyPath))
{
    return false;
}
```

**Comment by jborean93** [comment]
Thanks for picking that up, I've pushed a commit that fixes the logic and also mentions the reason why it's not using a single assembly in the approach https://github.com/jborean93/PowerShell-ALC/commit/4abcef43115b358ed0b9406a250600108ccee113. Now that the deps are loaded in the ALC in the ALCResolver approach it's less of a problem. I still personally believe the `ALCLoader` logic is better because the cmdlets can interact directly with the dependencies but it's certainly less of an issue going with `ALCResolver` if that's someone's preference.

**Comment by mdgrs-mei** [comment]
Now `pwsh.exe -File ./test.ps1 -Name ALCResolver` and `pwsh.exe -File ./test.ps1 -Name ALCLoader` shows the same result, thank you.

Following this, I think we can change this line. Deps will be always loaded in the ALC even if they are already available.

https://github.com/jborean93/PowerShell-ALC/blob/4abcef43115b358ed0b9406a250600108ccee113/ALCResolver/README.md?plain=1#L32

For the same reason, this line can be removed.

https://github.com/jborean93/PowerShell-ALC/blob/4abcef43115b358ed0b9406a250600108ccee113/README.md?plain=1#L48

**Comment by jborean93** [comment]
Done with https://github.com/jborean93/PowerShell-ALC/commit/1a5d41dd4012a1553ba8a45aa8c1b9b2ab8a3364. Thank you for picking them up.

**Comment by mdgrs-mei** [comment]
All resolved, thank you!
